# Generated by Django 3.2.12 on 2022-02-10 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crunch', '0002_auto_20220210_0503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='value',
        ),
        migrations.CreateModel(
            name='CharAttribute',
            fields=[
                ('attribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crunch.attribute')),
                ('value', models.CharField(max_length=1023)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('crunch.attribute',),
        ),
        migrations.CreateModel(
            name='FloatAttribute',
            fields=[
                ('attribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crunch.attribute')),
                ('value', models.FloatField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('crunch.attribute',),
        ),
        migrations.CreateModel(
            name='IntegerAttribute',
            fields=[
                ('attribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crunch.attribute')),
                ('value', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('crunch.attribute',),
        ),
    ]
