# Generated by Django 3.2.12 on 2022-02-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crunch', '0004_alter_attribute_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='snakefile',
            field=models.TextField(blank=True, default=''),
        ),
    ]
