# Generated by Django 3.2.12 on 2022-02-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crunch', '0006_auto_20220211_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='revision',
            field=models.CharField(blank=True, default='', help_text='The django-crunch git revision hash of the agent.', max_length=255),
        ),
        migrations.AddField(
            model_name='status',
            name='version',
            field=models.CharField(blank=True, default='', help_text='The django-crunch version number of the agent.', max_length=255),
        ),
    ]
