# Generated by Django 3.2.12 on 2022-02-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crunch', '0010_auto_20220214_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, default='', help_text='A short description in a sentence or more of this project.', max_length=1023),
        ),
        migrations.AddField(
            model_name='project',
            name='details',
            field=models.TextField(blank=True, default='', help_text='A detailed description of this project (written in Markdown).'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='description',
            field=models.CharField(blank=True, default='', help_text='A short description in a sentence or more of this dataset.', max_length=1023),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='details',
            field=models.TextField(blank=True, default='', help_text='A detailed description of this dataset (written in Markdown).'),
        ),
    ]
