# Generated by Django 3.2.12 on 2022-02-15 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crunch', '0011_auto_20220214_0654'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLAttribute',
            fields=[
                ('attribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crunch.attribute')),
                ('value', models.CharField(max_length=1023)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('crunch.attribute',),
        ),
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
    ]
