# Generated by Django 3.2.12 on 2022-03-07 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crunch', '0012_auto_20220215_0115'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatLongAttribute',
            fields=[
                ('attribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crunch.attribute')),
                ('latitude', models.DecimalField(decimal_places=9, help_text='The latitude of this location in decimal degrees.', max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=9, help_text='The longitude of this location in decimal degrees.', max_digits=12)),
            ],
            options={
                'abstract': False,
            },
            bases=('crunch.attribute',),
        ),
        migrations.AlterModelOptions(
            name='attribute',
            options={},
        ),
        migrations.AlterModelOptions(
            name='charattribute',
            options={},
        ),
        migrations.AlterModelOptions(
            name='floatattribute',
            options={},
        ),
        migrations.AlterModelOptions(
            name='integerattribute',
            options={},
        ),
        migrations.AlterModelOptions(
            name='urlattribute',
            options={},
        ),
    ]
