# Generated by Django 3.2.12 on 2022-03-08 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crunch', '0013_auto_20220307_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateTimeAttribute',
            fields=[
                ('attribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crunch.attribute')),
                ('value', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
            bases=('crunch.attribute',),
        ),
        migrations.AlterField(
            model_name='urlattribute',
            name='value',
            field=models.URLField(max_length=1023),
        ),
    ]
